# Prometheus Alert Rules for Secrets Rotation
# These alerts monitor secret rotation status based on metrics exposed by the secrets-exporter
#
# Deploy with: kubectl apply -f secrets-rotation.yaml -n monitoring

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: secrets-rotation-alerts
  namespace: monitoring
  labels:
    app: prometheus
    prometheus: main
    role: alert-rules
spec:
  groups:
    - name: secrets.rotation
      interval: 1h  # Check hourly
      rules:
        # ═══════════════════════════════════════════════════════════════════
        # CRITICAL ALERTS - Immediate action required
        # ═══════════════════════════════════════════════════════════════════

        - alert: SecretRotationOverdue
          expr: |
            madfam_secret_days_until_rotation < 0
          for: 1h
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Secret rotation is overdue: {{ $labels.secret_id }}"
            description: |
              Secret {{ $labels.secret_id }} in project {{ $labels.project }} is {{ $value | humanize }} days overdue for rotation.
              Owner: {{ $labels.owner }}
              Procedure: {{ $labels.procedure }}
              Risk Level: {{ $labels.risk_level }}

              Runbook: https://github.com/madfam/janua/blob/main/docs/runbooks/secrets/EMERGENCY_ROTATION.md
            runbook_url: "https://github.com/madfam/janua/blob/main/docs/runbooks/secrets/EMERGENCY_ROTATION.md"

        - alert: CriticalSecretOverdue
          expr: |
            madfam_secret_days_until_rotation < 0
            and on(secret_id) madfam_secret_risk_level{risk_level="critical"} == 1
          for: 30m
          labels:
            severity: critical
            team: security
            pagerduty: "true"
          annotations:
            summary: "CRITICAL secret rotation overdue: {{ $labels.secret_id }}"
            description: |
              A CRITICAL severity secret is overdue for rotation.
              Secret: {{ $labels.secret_id }}
              Project: {{ $labels.project }}
              Days overdue: {{ $value | humanize }}

              This requires immediate attention. Follow emergency rotation procedures.
            runbook_url: "https://github.com/madfam/janua/blob/main/docs/runbooks/secrets/EMERGENCY_ROTATION.md"

        # ═══════════════════════════════════════════════════════════════════
        # WARNING ALERTS - Action required soon
        # ═══════════════════════════════════════════════════════════════════

        - alert: SecretRotationDue3Days
          expr: |
            madfam_secret_days_until_rotation >= 0
            and madfam_secret_days_until_rotation <= 3
          for: 1h
          labels:
            severity: warning
            team: security
          annotations:
            summary: "Secret rotation due within 3 days: {{ $labels.secret_id }}"
            description: |
              Secret {{ $labels.secret_id }} needs rotation within {{ $value | humanize }} days.
              Project: {{ $labels.project }}
              Owner: {{ $labels.owner }}

              Schedule rotation soon to avoid security policy violations.
            runbook_url: "https://github.com/madfam/janua/blob/main/docs/runbooks/secrets/"

        - alert: SecretRotationDue7Days
          expr: |
            madfam_secret_days_until_rotation > 3
            and madfam_secret_days_until_rotation <= 7
          for: 1h
          labels:
            severity: warning
            team: infrastructure
          annotations:
            summary: "Secret rotation due within 7 days: {{ $labels.secret_id }}"
            description: |
              Secret {{ $labels.secret_id }} needs rotation within {{ $value | humanize }} days.
              Project: {{ $labels.project }}
              Owner: {{ $labels.owner }}

              Plan rotation during the next maintenance window.

        # ═══════════════════════════════════════════════════════════════════
        # INFO ALERTS - Upcoming rotations
        # ═══════════════════════════════════════════════════════════════════

        - alert: SecretRotationDue14Days
          expr: |
            madfam_secret_days_until_rotation > 7
            and madfam_secret_days_until_rotation <= 14
          for: 1h
          labels:
            severity: info
            team: infrastructure
          annotations:
            summary: "Secret rotation upcoming: {{ $labels.secret_id }}"
            description: |
              Secret {{ $labels.secret_id }} is due for rotation in {{ $value | humanize }} days.
              This is an informational alert to help with planning.

        # ═══════════════════════════════════════════════════════════════════
        # OPERATIONAL ALERTS - Rotation tracking
        # ═══════════════════════════════════════════════════════════════════

        - alert: SecretRotationFailed
          expr: |
            increase(madfam_secret_rotation_failures_total[1h]) > 0
          for: 5m
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Secret rotation failed: {{ $labels.secret_id }}"
            description: |
              Automated or manual secret rotation failed for {{ $labels.secret_id }}.
              Check rotation logs and retry manually if needed.

              Error: {{ $labels.error }}

        - alert: SecretExporterDown
          expr: |
            up{job="secrets-exporter"} == 0
          for: 15m
          labels:
            severity: warning
            team: infrastructure
          annotations:
            summary: "Secrets metrics exporter is down"
            description: |
              The secrets-exporter service is not responding.
              Secret rotation monitoring is degraded.

        - alert: TooManyOverdueSecrets
          expr: |
            count(madfam_secret_days_until_rotation < 0) > 5
          for: 1h
          labels:
            severity: critical
            team: security
          annotations:
            summary: "Multiple secrets are overdue for rotation"
            description: |
              {{ $value }} secrets are currently overdue for rotation.
              This indicates a systemic issue with the rotation process.

              Review SECRETS_REGISTRY.yaml and prioritize rotations.

    - name: secrets.compliance
      interval: 24h  # Daily compliance check
      rules:
        - alert: SecretRotationComplianceViolation
          expr: |
            count(madfam_secret_days_until_rotation < -30) > 0
          for: 1h
          labels:
            severity: critical
            team: security
            compliance: "true"
          annotations:
            summary: "Secrets rotation compliance violation"
            description: |
              {{ $value }} secrets are more than 30 days overdue for rotation.
              This may constitute a compliance violation.

              Immediate action required. Document in security incident log.

        - alert: WeeklyRotationSummary
          expr: |
            count(madfam_secret_days_until_rotation <= 7 and madfam_secret_days_until_rotation >= 0) > 0
          for: 1m
          labels:
            severity: none
            team: infrastructure
          annotations:
            summary: "Weekly secrets rotation summary"
            description: |
              {{ $value }} secrets are due for rotation in the next 7 days.
              Review and schedule rotations accordingly.
