# Janua - Enclii Service Manifest
# https://enclii.madfam.io
#
# This manifest defines the Janua authentication platform for Enclii deployment.
# Enclii handles: container orchestration, SSL/TLS, Cloudflare tunnel routing,
# health monitoring, and automated rollbacks.

version: "1.0"
project: janua
description: "Self-hosted OAuth2/OIDC authentication platform"

# =============================================================================
# Metadata
# =============================================================================
metadata:
  owner: madfam-org
  repository: https://github.com/madfam-org/janua
  documentation: https://docs.janua.dev
  license: AGPL-3.0
  port_block: 4100-4199  # MADFAM ecosystem allocation

# =============================================================================
# Services
# =============================================================================
services:
  # API Backend (FastAPI)
  janua-api:
    image: janua/api:latest
    port: 4100
    domain: api.janua.dev
    type: api
    healthcheck:
      path: /
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    resources:
      cpu: "2.0"
      memory: "2G"
      cpu_reservation: "1.0"
      memory_reservation: "1G"
    environment:
      - ENVIRONMENT=production
      - PORT=4100
    secrets:
      - DATABASE_URL
      - REDIS_URL
      - JWT_SECRET_KEY
      - SECRET_KEY
      - SENDGRID_API_KEY
      - SENTRY_DSN
      - RESEND_API_KEY
      - INTERNAL_API_KEY
    depends_on:
      - janua-postgres
      - janua-redis

  # User Dashboard (Next.js)
  janua-dashboard:
    image: janua/dashboard:latest
    port: 4101
    domain: app.janua.dev
    type: web
    healthcheck:
      path: /
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    resources:
      cpu: "1.0"
      memory: "512M"
      cpu_reservation: "0.5"
      memory_reservation: "256M"
    environment:
      - NODE_ENV=production
      - PORT=4101
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=https://api.janua.dev
      - NEXT_PUBLIC_APP_URL=https://app.janua.dev

  # Admin Panel (Next.js)
  janua-admin:
    image: janua/admin:latest
    port: 4102
    domain: admin.janua.dev
    type: web
    healthcheck:
      path: /
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    resources:
      cpu: "1.0"
      memory: "512M"
      cpu_reservation: "0.5"
      memory_reservation: "256M"
    environment:
      - NODE_ENV=production
      - PORT=4102
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=https://api.janua.dev
    access:
      - type: ip_whitelist
        ips:
          - "10.0.0.0/8"      # Internal network
          - "172.16.0.0/12"   # Docker networks
      - type: basic_auth
        enabled: true
        realm: "Janua Admin"

  # Documentation Site (Next.js/Fumadocs)
  janua-docs:
    image: janua/docs:latest
    port: 4103
    domain: docs.janua.dev
    type: web
    healthcheck:
      path: /
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    resources:
      cpu: "0.5"
      memory: "256M"
      cpu_reservation: "0.25"
      memory_reservation: "128M"
    environment:
      - NODE_ENV=production
      - PORT=4103
      - HOSTNAME=0.0.0.0
    cache:
      enabled: true
      ttl: 3600  # 1 hour for static docs

  # Marketing Website (Next.js)
  janua-website:
    image: janua/website:latest
    port: 4104
    domain: janua.dev
    type: web
    aliases:
      - www.janua.dev
    healthcheck:
      path: /
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    resources:
      cpu: "0.5"
      memory: "256M"
      cpu_reservation: "0.25"
      memory_reservation: "128M"
    environment:
      - NODE_ENV=production
      - PORT=4104
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=https://api.janua.dev
      - NEXT_PUBLIC_APP_URL=https://app.janua.dev
    cache:
      enabled: true
      ttl: 1800  # 30 minutes for marketing pages

# =============================================================================
# Data Services
# =============================================================================
data:
  # PostgreSQL Database
  janua-postgres:
    type: postgres
    version: "15"
    port: 5432
    internal: true
    storage:
      size: "50Gi"
      class: "ssd"
    backup:
      enabled: true
      schedule: "0 2 * * *"  # Daily at 2 AM
      retention: 30          # 30 days
    environment:
      POSTGRES_DB: janua
      POSTGRES_USER: janua
    secrets:
      - POSTGRES_PASSWORD

  # Redis Cache
  janua-redis:
    type: redis
    version: "7"
    port: 6379
    internal: true
    storage:
      size: "5Gi"
      class: "ssd"
    config:
      maxmemory: "512mb"
      maxmemory-policy: "allkeys-lru"
      appendonly: "yes"
    secrets:
      - REDIS_PASSWORD

# =============================================================================
# Networking
# =============================================================================
networking:
  mode: host  # Host network for Cloudflare tunnel compatibility
  tunnel:
    provider: cloudflare
    routes:
      - hostname: api.janua.dev
        service: janua-api
        port: 4100
      - hostname: app.janua.dev
        service: janua-dashboard
        port: 4101
      - hostname: admin.janua.dev
        service: janua-admin
        port: 4102
      - hostname: docs.janua.dev
        service: janua-docs
        port: 4103
      - hostname: janua.dev
        service: janua-website
        port: 4104
      - hostname: www.janua.dev
        service: janua-website
        port: 4104

# =============================================================================
# Deployment
# =============================================================================
deployment:
  strategy: rolling
  max_unavailable: 1
  max_surge: 1

  rollback:
    enabled: true
    on_failure: true
    history_limit: 5

  health_check:
    initial_delay: 60s
    success_threshold: 1
    failure_threshold: 3

  update:
    order:
      - janua-postgres  # Database first
      - janua-redis     # Cache second
      - janua-api       # API third (depends on data services)
      - janua-dashboard # Frontend services last
      - janua-admin
      - janua-docs
      - janua-website

# =============================================================================
# Monitoring
# =============================================================================
monitoring:
  prometheus:
    enabled: true
    port: 4190
    path: /metrics
    scrape_interval: 30s

  alerts:
    - name: janua-api-down
      condition: "up{service='janua-api'} == 0"
      duration: 1m
      severity: critical
      channels:
        - slack
        - pagerduty

    - name: janua-high-latency
      condition: "http_request_duration_seconds{quantile='0.95'} > 2"
      duration: 5m
      severity: warning
      channels:
        - slack

    - name: janua-error-rate
      condition: "rate(http_requests_total{status=~'5..'}[5m]) > 0.1"
      duration: 5m
      severity: warning
      channels:
        - slack

  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "5"
    aggregation:
      enabled: true
      destination: loki

# =============================================================================
# Secrets Management
# =============================================================================
secrets:
  provider: vault  # or: env, sealed-secrets, external-secrets
  path: secret/janua
  required:
    - DATABASE_URL
    - REDIS_URL
    - REDIS_PASSWORD
    - POSTGRES_PASSWORD
    - JWT_SECRET_KEY
    - SECRET_KEY
    - SENDGRID_API_KEY
    - RESEND_API_KEY
    - INTERNAL_API_KEY
  optional:
    - SENTRY_DSN
    - GRAFANA_PASSWORD

# =============================================================================
# Scaling (Future)
# =============================================================================
scaling:
  janua-api:
    min: 1
    max: 5
    metrics:
      - type: cpu
        target: 70
      - type: memory
        target: 80
      - type: http_requests
        target: 1000  # requests per second

  janua-dashboard:
    min: 1
    max: 3
    metrics:
      - type: cpu
        target: 70

  janua-website:
    min: 1
    max: 2
    metrics:
      - type: cpu
        target: 80
